#ifndef VS_CODE_INTELLISENSE_COMPAT_H
#define VS_CODE_INTELLISENSE_COMPAT_H

/*
 * Keil ARMCC __align(...) is not understood by MSVC-based C/C++ IntelliSense.
 * Referenced via .vscode/c_cpp_properties.json (forcedInclude), regenerated by fix_code_index.bat / generate_compile_commands.ps1.
 * Not used by Keil. Stripping __align restores parsing of USART buffers etc. for F12/navigation.
 */
#ifndef __align
#define __align(x)
#endif

/*
 * Keil ARM Compiler 5 头文件 / 内建关键字；Clang 无对应 ABI 修饰词，会报 unknown type / attribute。
 * 与 .vscode/c_cpp_properties.json 中 Template_Template 的 neutral 宏一致；Keil 工程不 include 本文件。
 */
#if !defined(__CC_ARM)
#ifndef __value_in_regs
#define __value_in_regs
#endif
#endif

#endif
